"""
This code was mainly generated by AI
and then manually edited to fit assignment specifications.

Run with:
python compute_analytics.py
"""

import json
from collections import Counter

ANALYTICS_FILE = "analytics.json"
OUTPUT_FILE = "analytics_compute.txt"

def load_analytics():
    with open(ANALYTICS_FILE, "r") as f:
        return json.load(f)

def main():
    data = load_analytics()

    lines = []

    # -----------------------------
    # 1. Unique pages
    # -----------------------------
    unique_pages = set(data.get("unique_pages", []))
    lines.append("=== Unique Pages ===")
    lines.append(f"Total unique pages (fragment removed): {len(unique_pages)}\n")

    # -----------------------------
    # 2. Longest page
    # -----------------------------
    longest_url, longest_count = data.get("longest_page", ["", 0])
    lines.append("=== Longest Page ===")
    lines.append(f"URL: {longest_url}")
    lines.append(f"Word count: {longest_count}\n")

    # -----------------------------
    # 3. Top 50 most common words
    # -----------------------------
    word_counts = data.get("word_counts", {})
    counter = Counter(word_counts)
    top_50 = counter.most_common(50)

    lines.append("=== Top 50 Most Common Words ===")
    for word, freq in top_50:
        lines.append(f"{word}: {freq}")
    lines.append("")

    # -----------------------------
    # 4. Subdomain counts
    # -----------------------------
    subdomains = data.get("subdomains", {})

    lines.append("=== Subdomains Under *.uci.edu ===")
    lines.append(f"Total subdomains: {len(subdomains)}\n")

    for subdomain in sorted(subdomains.keys()):
        lines.append(f"{subdomain}, {subdomains[subdomain]}")
    lines.append("")

    # -----------------------------
    # Write to file
    # -----------------------------
    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines))

    print(f"Analytics written to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
