"""
This code was mainly generated by AI
and then manually edited to fit assignment specifications.
"""

import re
import logging
import threading
from collections import defaultdict
from urllib.parse import urlparse, urljoin, urldefrag, parse_qs

from bs4 import BeautifulSoup

from tokenizer import tokenize
from utils.stopwords import load_stopwords
from analytics_store import load_analytics, save_analytics

from similarity_ngram import (
    make_ngrams,
    select_fingerprints,
    jaccard_similarity,
    FINGERPRINTS,
    NEAR_DUPLICATES
)

ALLOWED_DOMAINS = {
    "ics.uci.edu",
    "cs.uci.edu",
    "informatics.uci.edu",
    "stat.uci.edu"
}

STOPWORDS = load_stopwords()

# -----------------------------
# Logging: FOR TESTING PURPOSES
# -----------------------------
logger = logging.getLogger("crawler")
if not logger.handlers:
    logger.setLevel(logging.INFO)
    fmt = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")

    fh = logging.FileHandler("crawl_output.log", encoding="utf-8")
    fh.setFormatter(fmt)

    sh = logging.StreamHandler()
    sh.setFormatter(fmt)

    logger.addHandler(fh)
    logger.addHandler(sh)

# -----------------------------
# Analytics (shared state)
# -----------------------------
analytics = load_analytics() # Loads "analytics.json" from before.

UNIQUE_PAGES = set(analytics.get("unique_pages", [])) # No duplicates (as opposed to list) -> comparing members
WORD_COUNTS = defaultdict(int, analytics.get("word_counts", {})) # Word, Frequency; requires 2 variables
LONGEST_PAGE = tuple(analytics.get("longest_page", ["", 0])) # URL, Word Count; fixed pair that shows URL's longest page
SUBDOMAIN_COUNTS = defaultdict(int, analytics.get("subdomains", {})) # Subdomains, Frequency; requires 2 variables
# FINGERPRINTS = {k: set(v) for k, v in analytics["fingerprints"].items()}
NEAR_DUPLICATES = analytics.get("near_duplicates", []) # No duplicates (as opposed to list)

# Thread-safety for all shared analytics/similarity state 
ANALYTICS_LOCK = threading.Lock() # Prevent other threads from modifying.

# ============================================================
# SCRAPER
# ============================================================
def scraper(url, resp):
    """Core scraping function called by crawler."""
    
    # Process successful HTTP responses
    if resp.status != 200 or resp.raw_response is None:
        return [] # exit function early
    # Skip URLs that fail 
    if not is_valid(url):
        logger.info(f"Skip invalid URL (trap): {url}")
        return [] # exit function early

    logger.info(f"Processing: {url}")
    
     # Avoid non-HTML resources
    try:
        content_type = resp.raw_response.headers.get("Content-Type", "").lower() # Gathers the content-type from HTTP header
    except Exception:
        content_type = ""
        
    # Skip PDFs, images, etc.
    if "text/html" not in content_type: # If file lacks any text or HTML in content-type
        logger.info(f"Skip non-HTML ({content_type}): {url}")
        return [] # Then return early

    # Extract outgoing links from the page
    links = extract_next_links(url, resp)

    try:
        # Parse page content and extract visible text
        soup = BeautifulSoup(resp.raw_response.content, "html.parser") # Extracts data from HTML into a more readable format
        text = soup.get_text(separator=" ") # Replaces HTML tags with blankspace; ex. <p>Hello<b>world</b>!</p> -> Helloworld -> Hello World

        # Tokenize text
        tokens = tokenize(text, STOPWORDS) # Using RegEx

        # Normalize by removing fragment
        normalized_url, _ = urldefrag(url) # normalized_url = defragmented URL; _ = fragment

        # Update analytics
        with ANALYTICS_LOCK: # Ensures only one thread running
            # -----------------------------
            # Unique pages
            # -----------------------------
            is_new = normalized_url not in UNIQUE_PAGES
            if is_new:
                UNIQUE_PAGES.add(normalized_url)
                logger.info(f"New unique page ({len(UNIQUE_PAGES)}): {normalized_url}")

            # -----------------------------
            # Word counts
            # -----------------------------
            for t in tokens:
                WORD_COUNTS[t] += 1

            # -----------------------------
            # Longest page
            # -----------------------------
            global LONGEST_PAGE
            if len(tokens) > LONGEST_PAGE[1]:
                LONGEST_PAGE = (normalized_url, len(tokens))
                logger.info(f"New longest page: {normalized_url}")

            # -----------------------------
            # Subdomain counts
            # -----------------------------
            if is_new:
                domain = urlparse(normalized_url).netloc.lower() # netloc = domain, subdomain, port, credentials of URL 
                if domain.startswith("www."):
                    domain = domain[4:] # Starts after the www. which is 4 chars long
                if domain.endswith(".uci.edu"): # Ensures that crawler doesn't go beyond UCI websites
                    SUBDOMAIN_COUNTS[domain] += 1 

            # -----------------------------
            # Extra Credit Similarity (n-gram fingerprinting)
            # -----------------------------
            ngrams = make_ngrams(tokens)
            fingerprints = select_fingerprints(ngrams)
            FINGERPRINTS[normalized_url] = fingerprints

            for other_url, other_fp in FINGERPRINTS.items():
                if other_url == normalized_url:
                    continue
                sim = jaccard_similarity(fingerprints, other_fp) # SimilarityAB = jaccard(FingerprintA AND FingerprintB) / jaccard(FingerprintA OR FingerprintB)
                if sim > 0.90:
                    NEAR_DUPLICATES.append((normalized_url, other_url, sim))

            # -----------------------------
            # Updated analytics
            # -----------------------------
            analytics["unique_pages"] = list(UNIQUE_PAGES)
            analytics["word_counts"] = dict(WORD_COUNTS)
            analytics["longest_page"] = list(LONGEST_PAGE)
            analytics["subdomains"] = dict(SUBDOMAIN_COUNTS)
            # analytics["fingerprints"] = {k: list(v) for k, v in FINGERPRINTS.items()}
            analytics["near_duplicates"] = NEAR_DUPLICATES

            save_analytics(analytics)

    except Exception as e:
        logger.info(f"Error analyzing {url}: {e}")

    # Defragment and validate outgoing links
    cleaned = []
    for link in links:
        link, _ = urldefrag(link) # normalized_url = defragmented URL; _ = fragment
        if is_valid(link):
            cleaned.append(link)

    # Return URLs to be added to the frontier
    return cleaned


# ============================================================
# LINK EXTRACTION
# ============================================================
def extract_next_links(url, resp):
    """
    Extract all outgoing hyperlinks from an HTML page.
    Converts relative links to absolute URLs and removes fragments.
    Returns a list of URLs.
    """
    
    output_links = []

    try:
        # Parse raw HTML content
        soup = BeautifulSoup(resp.raw_response.content, "html.parser")

        # Find all anchor tags that contain an href attribute
        for tag in soup.find_all("a", href=True): # <a> is hyperlink & href (hypertext reference) is a link to other pages, so that they can be added to frontier
            href = tag.get("href")

            # Convert relative URLs to absolute URLs
            abs_url = urljoin(url, href) # Ensures that all URLs show the complete path to their resource
            """ Example:
            Relative URL: "../about"
            Absolute URL: "https://example.com/" + "../about" = https://example.com/about"
            """
            # Remove fragment identifiers
            abs_url, _ = urldefrag(abs_url)

            # Store extracted URL
            output_links.append(abs_url)

    except Exception:
        pass

    return output_links


# ============================================================
# TRAP DETECTION
# ============================================================
def is_redundant_trap_url(parsed):
    path = parsed.path.lower()
    query = parsed.query.lower()
    qs = parse_qs(parsed.query, keep_blank_values=True) # Stores a list of values from parsed URL, and ensures all parameters are preserved

    # WICS / NGS; WICS specifically leads to an infinite calendar trap & NGS is a blog, both are low info
    if "wics" in parsed.netloc or "ngs" in parsed.netloc: # netloc = Network Location of the parsed URL, the domain/subdomain/port/credentials
        return True

    # DokuWiki; Wiki leads to lots of redundant links and low info pages
    if "doku.php" in path:
        if not qs: # If it has no query parameters
            return False
        if set(k.lower() for k in qs.keys()) <= {"id"}: # if only query is "id," then it is OK
            return False
        return True

    # MediaWiki; Wiki leads to lots of redundant links and low info pages
    if path.endswith("index.php") and "title=" in query: # Pages with these parameters were specifically low info & too numerous
        allowed = {"title", "oldid"} # Parameters that pages of interest had
        if set(k.lower() for k in qs.keys()) <= allowed:
            return False
        return True

    # Trac Wiki: Overloads crawler with redundant URLs if path leads to...
    if "/wiki" in path:
        # Set of all keywords that want to be avoided under domains with "/wiki"
        bad = {"version", "format", "action", "from", "precision", "diff"}
        if any(k.lower() in bad for k in qs.keys()):
            return True

    # Timeline traps; often leads to infinite scrolling due to "from="
    if "timeline" in path and "from=" in query:
        return True

    # Tuple of UI parameters to avoid
    generic_bad = (
        "tab=",
        "sort=",
        "order=",
        "filter=",
        "replytocom=",
        "share=",
        "print="
    )

    # If query contains any of the UI parameters and more than 3 ampersands, which separates parameters...
    if any(k in query for k in generic_bad) and query.count("&") >= 3:
        return True
    
    if len(query) > 200: # Based on textbook suggestions
        return True

    # If none of the above trap detectors activate...
    return False


# ============================================================
# URL VALIDATION
# ============================================================
def is_valid(url):
    try:
        parsed = urlparse(url)

        if parsed.scheme not in {"http", "https"}:
            return False

        domain = parsed.netloc.lower() # netloc = domain, subdomain, port, credentials of URL 

        # Strips port if it is present
        domain = domain.split(":", 1)[0]

        # Removes "www." subdomain
        if domain.startswith("www."):
            domain = domain[4:]

        # Hardcoded: Blocks domains with "intranet" and "gitlab"; Deemed irrelevant as it overloads sites with low information URLs & info
        if domain == "intranet.ics.uci.edu": # Had a lot of pages + required UCI VPN access
            return False

        if domain == "gitlab.ics.uci.edu" or domain.endswith(".gitlab.ics.uci.edu"): # Had a page for every commit made
            return False

        # Domain boundary check: to avoid physics.uci.edu
        def allowed_domain(d: str) -> bool:
            # Checks if domain is one of the 4 domains being looked for
            return any(d == a or d.endswith("." + a) for a in ALLOWED_DOMAINS)

        if not allowed_domain(domain):
            return False

        # Hardcoded: ~eppstein/pix; Deemed irrelevant as it mostly contains photos
        if parsed.path.startswith("/~eppstein/pix"):
            return False

        if is_redundant_trap_url(parsed):
            return False

        path = parsed.path.lower()
        query = parsed.query.lower()
        q = parse_qs(parsed.query)

        # File extensions
        if re.match(
            r".*\.(css|js|bmp|gif|jpe?g|ico|png|tiff?"
            + r"|mp3|mp4|avi|mov|mpeg|pdf|docx?|xlsx?|pptx?"
            + r"|zip|rar|gz|tar|7z|exe)$",
            path
        ):
            return False

        # WordPress libraries; Archives overloaded with too many irrelevant pages
        if "/wp-content/" in path:
            return False

        # Calendar detection to avoid infinite loops
        if any(x in path for x in ["/events", "/calendar"]):
            return False

        if any(x in query for x in ["ical", "outlook"]):
            return False

        # Dates; Date patterns common in logs & archives that want to be avoided
        if re.search(r"^/(19|20)\d{2}/\d{1,2}/page/\d+(/|$)", path):
            return False

        # Page parameter whose number is greater than 100 should be avoided; pagination = number of branches/"nexts" to other pages
        if "paged" in q and any(v.isdigit() and int(v) >= 100 for v in q.get("paged", [])):
            return False

        # Query explosion; too many characters in query with more than 6 ampersands; from textbook
        if len(query) > 120 or query.count("&") > 6:
            return False

        # Deep pagination
        if re.search(r"(page|start)=\d{3,}", query):
            return False

        # Deep path
        if path.count("/") > 10:
            return False

        return True

    except TypeError:
        return False





