"""
This code was mainly generated by AI
and then manually edited to fit assignment specifications.
"""

import hashlib

# Number of bits in the fingerprint
SIMHASH_BITS = 64

def hash_word(word):
    """Hash a word into a 64-bit integer."""
    h = hashlib.sha1(word.encode("utf-8")).hexdigest()
    return int(h, 16) & ((1 << SIMHASH_BITS) - 1)

def simhash(tokens):
    """
    Compute the SimHash fingerprint for a list of tokens.
    Implements the algorithm described in Charikar (2002).
    """
    v = [0] * SIMHASH_BITS

    # Count word frequencies
    freq = {}
    for t in tokens:
        freq[t] = freq.get(t, 0) + 1

    # Build weighted vector
    for word, weight in freq.items():
        h = hash_word(word)
        for i in range(SIMHASH_BITS):
            bit = (h >> i) & 1
            if bit == 1:
                v[i] += weight
            else:
                v[i] -= weight

    # Final fingerprint
    fingerprint = 0
    for i in range(SIMHASH_BITS):
        if v[i] > 0:
            fingerprint |= (1 << i)

    return fingerprint

def hamming_distance(x, y):
    """Compute Hamming distance between two fingerprints."""
    return bin(x ^ y).count("1")