"""
This code was mainly generated by AI
and then manually edited to fit assignment specifications.
"""

import hashlib

# Parameters (tune if needed)
N_GRAM = 5          # 5-word shingles (textbook suggests 5–10)
P_MOD = 4           # select n-grams whose hash % p == 0

# Global storage
FINGERPRINTS = {}       # url -> set of selected hash values
NEAR_DUPLICATES = []    # (url1, url2, similarity)


def hash_ngram(ngram):
    """Hash an n-gram into a 64-bit integer."""
    h = hashlib.sha1(ngram.encode("utf-8")).hexdigest()
    return int(h, 16) & ((1 << 64) - 1)


def make_ngrams(tokens, n=N_GRAM):
    """Generate overlapping n-grams from tokens."""
    grams = []
    for i in range(len(tokens) - n + 1):
        grams.append(" ".join(tokens[i:i+n]))
    return grams


def select_fingerprints(ngrams, p=P_MOD):
    """
    Select fingerprints using the 0 mod p rule.
    This matches the textbook description exactly.
    """
    selected = set()
    for ng in ngrams:
        h = hash_ngram(ng)
        if h % p == 0:
            selected.add(h)
    return selected


def jaccard_similarity(set1, set2):
    """Compute Jaccard similarity between two fingerprint sets."""
    if not set1 or not set2:
        return 0.0
    inter = len(set1 & set2)
    union = len(set1 | set2)
    return inter / union
