"""
This code was mainly generated by AI
and then manually edited to fit assignment specifications.
"""

def load_stopwords(path="stopwords.txt"):
    with open(path, "r") as f:
        return set(w.strip().lower() for w in f.readlines())